clear;
clc;
T=readtable("heart.csv");
targetCol="target";
T.(targetCol)=categorical(T.(targetCol));
X=T(:, setdiff(T.Properties.VariableNames,targetCol));
Y=T.(targetCol);
X=table2array(X);
CV=cvpartition(Y,'HoldOut',0.2);
Xtrain=X(training(CV),:);
Ytrain=X(training(CV),:);
Xtest=X(test(CV),:);
Xtest=X(test(CV));
knnModel=fitcknn(Xtrain,Ytrain,"NumNeighbors",5);
Ypred=predict(KNNMatlab,Xtest);
accuracy=sum(Ypred==ytest)/nume(ytest)*100;
fprint("Knn accuracy:% 2f%%\n",accuracy);
confusionchart(Ytest,Ypred);
tittle("Knn confusion matrix");